export PATH=$HOME/.cargo/bin:$PATH

alias u="sudo pacman -Syu --noconfirm"
alias c="claude --dangerously-skip-permissions"
alias zs="vim ~/.zshrc"
alias zr="exec $SHELL && source ~/.zshrc"

autoload -Uz compinit
compinit
fpath=(/usr/share/zsh/site-functions $fpath)

#source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

if [[ -o login ]] && [[ -o interactive ]] && command -v aishell &>/dev/null; then
	exec aishell
fi

function setup() {
	ailog setup
	# --- login ---
	# ailog oauth $handle
	# ailog oauth $handle_bot --bot
	# --- login ---
	ailog gpt core -d
	ailog gpt memory -d
	aigpt setup
	claude
	ailog bot start --user
	ailog bot chat
}
