name: Build and Push Image
on: [ push ]

env:
  TAG: latest
  IMAGE_ID: aios
  IMAGE_NAME: ${{ gitea.repository }}
  APP_TOKEN: ${{ secrets.APP_TOKEN }}
  REGISTRY: localhost:8088

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: 
      image: syui/aios
      options: --privileged
    steps:
      - name: Initialize
        run: |
          pacman -Syuu --noconfirm base-devel archiso docker git curl
          docker pull syui/aios
          docker tag syui/aios  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          echo "${{ env.APP_TOKEN }}" | docker login ${{ env.REGISTRY }} -u syui --password-stdin
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

