name: release

on:
  push:

env:
  TAG: latest
  IMAGE_NAME: ${{ gitea.repository }}
  REGISTRY: git.syui.ai

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syui/aios
      options: --privileged
    steps:
      - name: Push image to Gitea container registry
        run: |
          pacman -Sy --noconfirm docker
          docker pull ghcr.io/syui/aios
          docker tag ghcr.io/syui/aios ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ gitea.actor }} --password-stdin
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
