# /etc/aipkg.conf (pacman.conf と同じ書き方)
# $repo はリポジトリ名、$arch は aarch64 に置き換わる

[options]
Architecture = aarch64

[aios]
# まだネットワークがないので file:// だけ使える
Server = https://git.syui.ai/ai/repo/raw/branch/main/$arch
