[package]
name = "aish-sys"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aish-plugin.workspace = true
libc = "0.2"
gimli = { version = "0.31", default-features = false, features = ["read"] }
object = { version = "0.36", default-features = false, features = ["read_core", "elf"] }
serde_json.workspace = true
