[package]
name = "aios"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "aios"
path = "src/main.rs"
test = false
bench = false

[dependencies]
smoltcp = { version = "0.12", default-features = false, features = ["alloc", "medium-ethernet", "proto-ipv4", "proto-dhcpv4", "socket-tcp", "socket-udp", "socket-icmp", "socket-dhcpv4"] }
