[package]
name = "aios-user"
version = "0.0.1"
edition = "2024"
license = "MIT"

[[bin]]
name = "init"
path = "src/bin/init.rs"

[profile.release]
panic = "abort"
opt-level = "s"
strip = true

[[bin]]
name = "which"
path = "src/bin/which.rs"

[[bin]]
name = "hello"
path = "src/bin/hello.rs"

[[bin]]
name = "aish"
path = "src/bin/aish/main.rs"

[[bin]]
name = "aipkg"
path = "src/bin/aipkg.rs"

[[bin]]
name = "fetch"
path = "src/bin/fetch.rs"

[[bin]]
name = "systemctl"
path = "src/bin/systemctl.rs"

[[bin]]
name = "journalctl"
path = "src/bin/journalctl.rs"

[[bin]]
name = "login"
path = "src/bin/login.rs"

[[bin]]
name = "passwd"
path = "src/bin/passwd.rs"

[[bin]]
name = "su"
path = "src/bin/su.rs"

[[bin]]
name = "mkswap"
path = "src/bin/mkswap.rs"

[[bin]]
name = "swapon"
path = "src/bin/swapon.rs"

[[bin]]
name = "free"
path = "src/bin/free.rs"

[[bin]]
name = "resize"
path = "src/bin/resize.rs"

[[bin]]
name = "aios"
path = "src/bin/aios.rs"

[[bin]]
name = "ip"
path = "src/bin/ip.rs"

[[bin]]
name = "networkd"
path = "src/bin/networkd.rs"

[[bin]]
name = "modprobe"
path = "src/bin/modprobe.rs"

[[bin]]
name = "chsh"
path = "src/bin/chsh.rs"

[[bin]]
name = "useradd"
path = "src/bin/useradd.rs"

[dependencies]
libc = "0.2"
ruzstd = "0.9"
tar = { version = "0.4", default-features = false }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
sha2 = { version = "0.10", default-features = false }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
webpki-roots = "1"

